version: '3.1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: twitterdb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - ~/data:/data/db
    networks:
      - backend
  tweepy:
    build: 
      context: ./tweepy
    container_name: tweepy
    restart: always
    environment:
      - CONSUMER_KEY="jI33n8S65TccdRvulbunjA4kh"
      - CONSUMER_SECRET="6r6AsE8FXdoIDikb8NZn1IIqJsCO8eoePz1OVH2ekelApnxmVW"
      - ACCESS_TOKEN="1206531229300019201-u1m8qlRyruKp1hC8tGeQAud7LSlgzj"
      - ACCESS_TOKEN_SECRET="3zUX38inYV8FlwTBxT8eZNuJdFFMKX8AD7yrE2GvDzcNq"
    links:
      - mongodb
    networks:
      - backend
  query:
    build:
      context: ./query
    container_name: query
    restart: always
    links:
      - mongodb
    volumes: 
      - ./usernames.html:/tmp/usernames.html
    networks:
      - backend
  apache:
    image: httpd:2.4
    container_name: apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./usernames.html:/usr/local/apache2/htdocs/index.html
    networks:
      - backend
networks:
  backend:
    driver: "bridge"

