version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: twitter-db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init-test.js:/tmp/test.js
      - ~/data:/data/db
