version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admiin
      - MONGO_INITDB_DATABASE=twitter-db
    ports:
      - 27017:27017
    volumes:
      - ~/data:/data/db

