# configure docker daemon
  - name: Deploy Docker daemon.json.
    host: localhost
    copy:
      src: files/daemon.json
      dest: /etc/docker/daemon.json

# docker-compose up
- name: run the service defined in my_project's docker-compose.yml
  host: localhost
  docker_compose:
    project_src: /path/to/my_project

